apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pruebakubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: villaltajose/backt
        ports:
        - containerPort: 8080
